#!/usr/bin/env bash

{
  title() {
    printf "   ___       __                        __       \n"
    printf "  / _ |__ __/ /____  ___  _______ ____/ /__ ____\n"
    printf " / __ / // / __/ _ \/ _ \\/ __/ _ \\/ _  / -_) __/\n"
    printf "/_/ |_\\_,_/\\__/\\___/\\_, /_/  \\_,_/\\_,_/\\__/_/\n"
    printf "                   /___/\n\n"
    printf "             Machine Structures\n"
    printf "     Great Ideas in Computer Architecture\n"
    printf "               Project 2: CPU\n\n\n"
  }

  title
  python3 tests/check.py
}
